- app/Resources/views/base.html.twig
informational links
- Demo
- Github
- Gitter
- Twitter
> [#35] [#39] Template layout with bootstrap

- .travis.yml
This will allow chats to be public
> Removed Slack integration & added Gitter

- app/Resources/views/base.html.twig
- src/DashboardHub/Bundle/AppBundle/Resources/views/Default/index.html.twig
* CSS include
* Icons sprinkled through App
> [#51] FontAwesome Icons added

- README.md
Spelling mistake fix on readme
> Fix sp in anchor

- web/app_dev.php
Please see comments on Issue 69.
> Allow SYMFONY_ENV to force dev environment

- README.md
- web/app_dev.php
After changes to app_dev.php for dev ENV variable, ENV variable is
always required
> [#71] How to run builtin webserver

- app/Resources/views/base.html.twig
- src/DashboardHub/Bundle/AppBundle/Controller/GithubController.php
- src/DashboardHub/Bundle/AppBundle/Resources/public/css/styles.css
- src/DashboardHub/Bundle/AppBundle/Resources/views/Github/tile/currentMilestone.html.twig
- src/DashboardHub/Bundle/AppBundle/Resources/views/Github/tile/latestEvent.html.twig
- src/DashboardHub/Bundle/AppBundle/Resources/views/Template/Github.html.twig
- src/DashboardHub/Bundle/AppBundle/Resources/views/Template/header.html.twig
> Feature/86 enhance GitHub theme

- app/Resources/views/base.html.twig
> [105] Links added to footer

- pom.xml
- src/main/resources/META-INF/additional-spring-configuration-metadata.json
Custom configuration is now known to the application...
> Custom configuration meta data added to application

- api/environments/create.js
- api/environments/deployed/create.js
- api/environments/tokens/create.js
- api/environments/update.js
- api/models/deployed.js
- api/models/environment.js
Closes #354 
The UI does NOT action accordingly to API errors, this will be done in #326
> Validation moved to models

- web/package-lock.json
- web/package.json
- web/src/app/app.module.ts
- web/src/app/auth/profile/profile.component.html
> Improved profile page

- Makefile
- README.md
- api/README.md
> Improvements to local development docs and make commands

- web/src/app/app.component.css
- web/src/app/app.component.html
- web/src/app/app.module.ts
- web/src/app/environments/environment-add/environment-add.component.html
- web/src/app/environments/environment-list/environment-list.component.css
- web/src/app/environments/environment-list/environment-list.component.html
- web/src/app/pricing/pricing.component.css
- web/src/app/pricing/pricing.component.html
- web/src/app/pricing/pricing.component.ts
> Footer and pricing

- web/package-lock.json
- web/src/app/app.module.ts
- web/src/app/environments/tokens/token-list/token-list.component.html
- web/src/app/environments/tokens/token-list/token.list.component.ts
- web/src/app/pricing/pricing.component.html
> Example beacon command in token section

- web/src/app/environments/tokens/token-list/token.list.component.ts
> Fixed environment.id on example curl usage in token list

- README.md
- web/README.md
- web/src/app/environments/deployed/deployed-list/deployed-list.component.html
- web/src/app/environments/deployed/deployed-summary/deployed-summary.component.html
- web/src/app/environments/environment-add/environment-add.component.html
- web/src/app/environments/environment-edit/environment-edit.component.html
- web/src/app/environments/tokens/token-add/token-add.component.html
- web/src/app/environments/tokens/token-list/token-list.component.html
> Sprinkle inline docs / tips to help user

- web/src/app/environments/environment-view/environment-view.component.html
> Latest release info on environment view

- web/src/app/environments/environment-list/environment-list.component.html
> Button added to environment list to view details

- api/environments/summary.js
> Fixed defect if no my environments

- web/src/app/environments/environment-add/environment-add.component.html
- web/src/app/environments/environment-edit/environment-edit.component.html
> Improved info on add/edit environment page

- web/src/app/app.component.ts
- web/src/app/app.module.ts
- web/src/app/environments/deployed/deployed-add/deployed-add.component.css
- web/src/app/environments/deployed/deployed-add/deployed-add.component.html
- web/src/app/environments/deployed/deployed-add/deployed-add.component.ts
- web/src/app/environments/deployed/deployed-list/deployed-list.component.html
- web/src/app/environments/deployed/deployed-list/deployed.list.component.ts
- web/src/app/environments/deployed/deployed-summary/deployed-summary.component.html
- web/src/app/environments/deployed/deployed-summary/deployed-summary.component.ts
- web/src/app/environments/deployed/deployed.service.ts
- web/src/app/environments/deployed/state.ts
- web/src/app/environments/environment-view/environment-view.component.ts
- web/src/app/environments/environments.service.ts
- web/src/app/environments/tokens/token-add/token-add.component.css
- web/src/app/environments/tokens/token-list/token-list.component.html
- web/src/app/environments/tokens/token-list/token.list.component.ts
- web/src/app/environments/tokens/token.component.ts
> Add Deployed release from the UI

- api/environments/list.js
> Specify attributes for environment lists

- web/src/app/auth/auth.guard.ts
- web/src/app/environments/deployed/deployed.service.ts
- web/src/app/environments/tokens/tokens.service.ts
> #479 Snackbar notification for Release/Token activity

- Makefile
- api/environments/deployed/create.js
- api/environments/list.js
- api/environments/releases/list.js
- api/models/deployed.js
- web/src/app/environments/deployed/deployed-add/deployed-add.component.html
- web/src/app/environments/deployed/deployed.service.ts
- web/src/app/environments/environment-list/environment-list.component.html
> Failure states

- README.md
> make api clean command added to docs

- api/environments/create.js
- api/environments/monitors/create.js
- api/environments/monitors/ping.js
- api/models/monitored.js
- api/serverless.yml
- web/src/app/environments/monitors/monitor-add/monitor-add.component.html
- web/src/app/environments/monitors/monitor-list/monitor-list.component.html
- web/src/app/environments/monitors/monitor.ts
- web/src/app/environments/monitors/monitors.service.ts
> Ping monitors

- web/src/app/pricing/pricing.component.html
> Updating pricing, free to include 1 monitor 

- web/src/app/pricing/pricing.component.html
> Updated pricing for free account, to have unlimited followers

- api/models/environment.js
- web/src/app/environments/deployed/deployed-list/deployed-list.component.html
- web/src/app/environments/deployed/deployed-summary/deployed-summary.component.html
- web/src/app/environments/environment-list/environment-list.component.html
> Release / Deploys if failed show in red

- web/src/app/environments/deployed/deployed-add/deployed-add.component.html
- web/src/app/environments/monitors/monitor-add/monitor-add.component.html
- web/src/app/environments/tokens/token-add/token-add.component.html
- web/src/app/environments/tokens/token-list/token-list.component.html
> Monitor to display more info

- api/README.md
> Documentation

- README.md
> Technology used logos added to readme

- api/models/deployed.js
- web/src/app/environments/deployed/deployed-add/deployed-add.component.html
> Increased deploy release version from 32 to 64

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Relates to #565 and #566 
- Issue template
- Pull request template
> Templates for issues and pull requests

- api/environments/create.js
- api/environments/list.js
- api/environments/update.js
- api/models/environment.js
- web/src/app/environments/environment-add/environment-add.component.html
- web/src/app/environments/environment-edit/environment-edit.component.html
- web/src/app/environments/environment.ts
- web/src/app/environments/environments.service.ts
Relates to #547 
- `logo` field added to the api model
- `logo` field added to the `create environment` on the UI
- `logo` field added to the `update environment` on the UI
> Logo field added to the environment model

- web/src/app/main/content/environment/environment-list/environment-list.component.html
- web/src/app/main/content/environment/sidenav/environment-sidenav.component.html
> Monitoring removed from Environment side nav

- api/models/environment.js
- web/src/app/main/content/environment/environment-add/environment-add.component.html
- web/src/app/main/content/environment/environment-edit/environment-edit.component.html
> #634 Logo url validation for https

- web/src/index.html
> #643 Gitter side panel chat added

- web/src/app/app.component.ts
- web/src/app/app.module.ts
- web/src/index.html
> #592 google analytics added

- web/src/app/main/content/help/help.component.ts
- web/src/assets/help/environment-types.md
- web/src/assets/help/quickstart.md
- web/src/index.html
> Deploy Google analytics to production

- api/environments/get.js
- api/serverless.yml
- data/environments.json
- web/src/app/main/content/environment/environment-list/environment-list.component.html
- web/src/app/main/content/environment/environment-view/environment-details/environment-details.component.html
- web/src/app/main/content/environment/environment-view/environment-details/environment-details.component.ts
- web/src/app/main/content/environment/environment-view/environment-view.component.html
- web/src/app/main/content/environment/environment-view/private.environment.resolver.ts
- web/src/app/main/content/environment/environment.service.ts
- web/src/app/main/content/environment/overview/overview.component.html
- web/src/app/main/content/environment/overview/overview.component.ts
- web/src/app/main/content/environment/overview/public.environment.resolver.ts
- web/src/app/main/main.module.ts
- web/src/environments/environment.prod.ts
- web/src/environments/environment.ts
RELATES TO #489 
This also improves the owners view of the details page...
> View details of public environments

- api/environments/get.js
- api/models/environment.js
- data/environments.json
- web/src/app/main/content/environment/environment-view/environment-details/environment-details.component.html
- web/src/app/main/content/environment/environment.ts
> #651 View statistics

- web/src/app/main/content/environment/environment-list/environment-list.component.html
- web/src/app/main/content/environment/environment-list/environment-list.component.scss
- web/src/app/main/content/environment/environment-list/environment-list.component.ts
- web/src/app/main/content/environment/environment-private-list/environment-private-list.component.html
- web/src/app/main/content/environment/environment-private-list/environment-private-list.component.ts
- web/src/app/main/content/environment/environment-public-list/environment-public-list.component.html
- web/src/app/main/content/environment/environment-public-list/environment-public-list.component.ts
- web/src/app/main/main.module.ts
> #668 #669 Refresh public & private environment list

- api/environments/get.js
> fix(environment): #675 public view update environment no datetime

- .github/CONTRIBUTING.md
- README.md
> docs: #619 Conventional changelog added for commits

- .github/CONTRIBUTING.md
- README.md
> docs: #619 improved contribution commit example

- api/environments/monitors/pinged/ping.js
- api/models/pinged.js
- data/pinged.json
- web/src/app/main/content/environment/sidenav/environment-sidenav.component.html
> feat(ttl) #680 monitoring pings have a ttl of 1 day

- api/config.json
- api/environments/monitors/pinged/ping.js
- api/models/pinged.js
- web/src/app/main/content/environment/monitor/pinged/pinged.service.ts
> Fixed datetime on ttl for pimg

- api/config.json
- api/environments/monitors/create.js
- api/environments/monitors/delete.js
- api/environments/monitors/pinged/ping.js
- api/models/deployed.js
- web/src/app/main/content/environment/environment-list/environment-list.component.html
- web/src/app/main/content/environment/monitor/monitor.component.html
- web/src/app/main/content/environment/monitor/monitor.component.ts
- web/src/app/main/content/environment/monitor/monitor.ts
- web/src/app/main/content/pricing/pricing.component.html
closes #687 
Dependent on #685 
> Highlight red if latest Deploy or Monitor fails

- web/src/app/main/error.http.interceptor.ts
- web/src/app/main/main.module.ts
> feat(http): error handling with snackbar

- api/environments/releases/list.js
- data/deployed.json
- web/src/app/main/content/environment/deployed/release.ts
- web/src/app/main/content/environment/deployed/release/release.component.html
- web/src/app/main/content/environment/deployed/release/release.component.ts
> feat(release): line graph of release data

- api/environments/releases/list.js
- data/deployed.json
- web/src/app/main/content/environment/deployed/release.ts
- web/src/app/main/content/environment/deployed/release/release.component.html
- web/src/app/main/content/environment/deployed/release/release.component.ts
- web/src/app/main/content/environment/monitor/monitor.component.html
- web/src/app/main/content/environment/monitor/monitor.component.ts
- web/src/app/main/content/environment/monitor/pinged/pinged.ts
- web/src/app/main/main.module.ts
> feat(monitoring): line graph of monitoring data

- README.md
Adds an additional screenshot showing the release page.
> Adds Release page screenshot.

- README.md
Adding a link to FAQ section to easily view them.
> Add FAQ link

- .travis.yml
> fix(ci): only unencrypt if doing a deploy

- web/src/app/main/content/environment/deployed/release/release.component.ts
> Changed release graph labels to 's'

- web/src/app/main/content/environment/environment-public-list/environment-public-list.component.html
- web/src/app/main/content/environment/environment-public-list/environment-public-list.component.ts
> feat(environments): bar graph for environment list releases

- web/src/app/main/content/environment/environment-add/environment-add.component.html
- web/src/app/main/content/environment/environment-edit/environment-edit.component.html
> fix(logo): regex fix for https logo url

- web/src/app/main/content/pricing/pricing.component.html
> feat(pricing): change text

- api/environments/releases/list.js
- web/src/app/main/content/environment/monitor/monitor.component.html
- web/src/app/main/content/environment/monitor/monitor.component.ts
> Monitoring improvements

- web/src/app/main/content/environment/monitor/monitor.component.ts
> fix(monitoring) monitoring delete and form reset

- web/src/app/main/content/environment/monitor/monitor.component.ts
> Deploy to production

- web/src/app/main/content/environment/token/token.service.ts
> fix(token): using correct http client

- api/README.md
- web/src/app/main/content/environment/token/token.component.ts
> Deploy token CRUD fix to pro

- web/src/app/main/content/environment/environment-add/environment-add.component.html
- web/src/app/main/content/environment/environment-private-list/environment-private-list.component.html
- web/src/app/main/content/environment/environment-public-list/environment-public-list.component.html
> fix(scrolling): whole page now scrolls

- web/src/app/main/content/environment/environment-add/environment-add.component.html
- web/src/app/main/content/environment/environment-private-list/environment-private-list.component.html
- web/src/app/main/content/environment/environment-public-list/environment-public-list.component.html
- web/src/app/main/content/environment/token/token.component.ts
> Deploy scrolling fix to prod

- Makefile
- README.md
> fix(deployment): fix renaming of pem files

- README.md
> added social media links to readme.md

- .travis.yml
> fix(ci): build ui before running tests

- api/src/environments/monitors/pinged/ping.js
> fix(monitoring): fixed monitoring bug for cron

- web/src/app/main/content/help/help.component.ts
- web/src/assets/help/ci-usage.md
> #681 Example CI usage for TravisCI & Circle

- Makefile
- api/config.json.tpl
- api/serverless.yml
- api/src/models/project.js
- api/src/projects/create.js
- api/src/projects/delete.js
- api/src/projects/get.js
- api/src/projects/list.js
- api/src/projects/update.js
- api/tests/features/environments/list-private.feature
- api/tests/features/environments/update.feature
- api/tests/features/projects/create.feature
- api/tests/features/projects/delete.feature
- api/tests/features/projects/get-private.feature
- api/tests/features/projects/get-public.feature
- api/tests/features/projects/list-private.feature
- api/tests/features/projects/list-public.feature
- api/tests/features/projects/update.feature
- data/projects.json
> API CRUD for Projects

- web/src/app/main.component.html
- web/src/app/main.component.ts
> feat(version): display build version number

- web/src/app/app.module.ts
- web/src/app/interceptors/error.http.interceptor.ts
- web/src/app/main.component.html
> feat(error): #813 interceptor for handling api errors

- api/src/environments/get.js
- api/tests/features/environments/get-private.feature
- api/tests/features/environments/get-public.feature
- web/src/app/app.module.ts
- web/src/app/app.routes.ts
- web/src/app/dashboard/dashboard.component.html
- web/src/app/environments/environment.model.ts
- web/src/app/environments/environment.service.ts
- web/src/app/environments/list-public/environments-list-public.component.html
- web/src/app/environments/list-public/environments-list-public.component.ts
- web/src/app/environments/monitors/monitor.model.ts
- web/src/app/environments/monitors/pinged.model.ts
- web/src/app/environments/releases/deployed.model.ts
- web/src/app/environments/tokens/token.model.ts
- web/src/app/environments/view/environments-view.component.html
- web/src/app/environments/view/environments-view.component.ts
- web/src/app/environments/view/public.environment.resolver.ts
- web/src/app/main.component.html
closes #799 
closes #817 
closes #818 
> feat(environment) #799 view environment details

- web/src/app/environments/environment.service.ts
- web/src/app/interceptors/api.http.interceptor.ts
> fix(http): #821 http interceptor looks for '{api}'

- web/src/app/app.module.ts
- web/src/app/app.routes.ts
- web/src/app/auth/auth.guard.ts
- web/src/app/environments/environment.service.ts
- web/src/app/environments/list-public/environments-list-public.component.html
- web/src/app/main.component.ts
> feat(private): #826 protect private pages

- web/src/app/environments/list/environments-list.component.html
> feat(responsive): #833 environment list removed data for mobile

- web/src/app/app.module.ts
- web/src/app/app.routes.ts
- web/src/app/auth/auth.service.ts
- web/src/app/auth/profile.ts
- web/src/app/auth/profile/profile.resolver.ts
- web/src/app/environments/add/environments-add.component.ts
- web/src/app/environments/environment.model.ts
- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/list/environments-list.component.ts
- web/src/app/environments/list/private/environments-list-private.component.html
- web/src/app/environments/list/private/environments-list-private.component.ts
- web/src/app/environments/list/private/private.environments.resolver.ts
- web/src/app/environments/list/public/environments-list-public.component.ts
- web/src/app/environments/list/public/public.environments.resolver.ts
- web/src/app/environments/releases/deployed.model.ts
- web/src/app/environments/view/environments-view.component.html
- web/src/app/environments/view/environments-view.component.ts
- web/src/app/environments/view/private/environments-view-private.component.html
- web/src/app/environments/view/private/environments-view-private.component.ts
- web/src/app/environments/view/private/private.environment.resolver.ts
- web/src/app/environments/view/public/environments-view-public.component.html
- web/src/app/environments/view/public/environments-view-public.component.ts
- web/src/app/environments/view/public/public.environment.resolver.ts
- web/src/app/main.component.ts
> feat(environment): #831 view private environment

- README.md
- api/src/environments/tokens/create.js
- api/tests/features/environments/tokens/create.feature
- web/src/app/app.module.ts
- web/src/app/app.routes.ts
- web/src/app/environments/add/environments-add.component.html
- web/src/app/environments/edit/environments-edit.component.html
- web/src/app/environments/list/private/environments-list-private.component.html
- web/src/app/environments/list/public/environments-list-public.component.html
- web/src/app/environments/tokens/environments-tokens.component.html
- web/src/app/environments/tokens/environments-tokens.component.ts
- web/src/app/environments/tokens/token.form.ts
- web/src/app/environments/tokens/token.model.ts
- web/src/app/environments/tokens/token.service.ts
- web/src/app/environments/tokens/tokens.resolver.ts
- web/src/app/environments/view/environments-view.component.html
- web/src/app/environments/view/private/environments-view-private.component.html
- web/src/app/environments/view/public/environments-view-public.component.html
> feat(tokens): #801 CRUD tokens for environment

- web/src/app/environments/list/environments-list.component.html
> feat(environments): #854 show environment latest state on list

- web/src/app/app.module.ts
- web/src/app/environments/environment.model.ts
- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/releases/state.pipe.ts
- web/src/app/environments/type.pipe.ts
> feat(environment): #856 environment type and release state pipe

- web/package-lock.json
- web/package.json
- web/src/app/environments/monitors/view/monitors-view.component.html
- web/src/app/main.component.ts
> Auth0 upgrade, profile page removed

- web/src/app/app.module.ts
- web/src/app/app.routes.ts
- web/src/app/environments/list/environments-list.component.html
- web/src/app/legal/terms-conditions/terms-conditions.component.html
- web/src/app/legal/terms-conditions/terms-conditions.component.ts
- web/src/app/main.component.ts
> feat(terms-conditions): #597 Added terms and conditions page

- web/src/app/app.module.ts
- web/src/app/app.routes.ts
- web/src/app/legal/privacy/privacy.component.html
- web/src/app/legal/privacy/privacy.component.ts
- web/src/app/main.component.ts
> feat(privacy): #596 privacy page

- api/src/environments/monitors/create.js
- api/src/environments/monitors/list.js
- api/src/environments/monitors/pinged/ping.js
- api/tests/features/environments/monitors/pinged/ping.feature
- web/src/app/environments/monitors/list/monitors-list.component.html
> feat(monitors): #847 ping total added to monitor

- README.md
> docs: #880 running API automated tests

- web/src/assets/help/quickstart.md
> feat(docs): #866 updated quickstart docs

- web/src/app/auth/auth.service.ts
- web/src/app/environments/view/environments-view.component.ts
- web/src/app/interceptors/api.http.interceptor.ts
- web/src/app/interceptors/error.http.interceptor.ts
- web/src/app/main.component.html
> bug(auth): #897 sync user info on layout

- web/src/app/environments/monitors/list/monitors-list.component.html
> feat(monitors): #906 swapped positions of path and status code around

- web/src/app/app.module.ts
- web/src/app/dialog/confirmation/dialog-confirmation.component.html
- web/src/app/dialog/confirmation/dialog-confirmation.component.ts
- web/src/app/environments/monitors/view/monitors-view.component.html
- web/src/app/environments/monitors/view/monitors-view.component.ts
- web/src/app/environments/tokens/environments-tokens.component.html
- web/src/app/environments/tokens/environments-tokens.component.ts
- web/src/app/environments/view/private/environments-view-private.component.html
- web/src/app/environments/view/private/environments-view-private.component.ts
> #894: Confirm delete messages when deleting tokens, monitors & environments

- api/src/environments/update.js
- web/src/app/environments/view/environments-view.component.html
- web/src/app/environments/view/private/environments-view-private.component.ts
>  fix(environment): #905 update link/url for environment

- web/src/app/environments/list/private/environments-list-private.component.ts
- web/src/app/environments/list/public/environments-list-public.component.ts
- web/src/app/environments/monitors/list/monitors-list.component.ts
- web/src/app/environments/monitors/view/monitors-view.component.ts
- web/src/app/environments/view/private/environments-view-private.component.ts
- web/src/app/environments/view/public/environments-view-public.component.ts
>  feat(environment): #554 refresh data every 30s

- web/src/app/auth/auth.service.ts
- web/src/app/auth/callback/callback.component.html
- web/src/app/auth/callback/callback.component.ts
> fix(auth): #910 redirect if auth callback falls

- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/tokens/environments-tokens.component.html
- web/src/assets/help/welcome-message.md
@eddiejaoude The issue here is that I would like to NOT hard code the welcome message onto the homepage, so I decided to create a separate file called welcome-message.md - however, I wasn't sure how to redirect environments-list.component.html to look at welcome-message.md - had a look at stackoverflow but I think the answers were overcomplicating the issue and I couldn't figure it out :(
> feat(docs): #891 add new welcome-message file

- web/src/app/environments/add/environments-add.component.html
- web/src/app/environments/environment.form.ts
- web/src/app/help/help.component.ts
- web/src/assets/help/create-environment.md
> feat(docs): #653 create environment docs

- web/src/app/help/help.component.ts
- web/src/assets/help/edit-environment.md
> feat(docs): #654 edit enrivonment docs

- web/src/app/help/help.component.ts
- web/src/assets/help/delete-environment.md
> feat(docs): #655 delete environment docs

- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/list/public/environments-list-public.component.html
- web/src/app/environments/list/public/environments-list-public.component.ts
- web/src/app/environments/tokens/environments-tokens.component.html
- web/src/app/help/help.component.ts
>  feat(environment): #920 moved welcome message to public & add button

- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/monitors/list/monitors-list.component.html
- web/src/app/environments/view/environments-view.component.html
> fix(pings): #819 undo changes committed to wrong branch

- web/src/app/environments/edit/environments-edit.component.html
- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/view/environments-view.component.html
> feat(environments): #922 fix conditions for red text

- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/view/environments-view.component.html
- web/src/app/main.component.ts
> feat(environments): #925 orange environment name when deploy or build in progress

- web/src/app/environments/monitors/monitor.form.ts
> fix(ping): #936 Sned monitor status as int not string

- web/src/app/auth/login/login.component.html
- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/list/public/environments-list-public.component.html
- web/src/app/environments/tokens/environments-tokens.component.html
> feat(environments): #953 helper info on landing page

- .travis.yml
- Makefile
> feat(ci): #965 bumped version to v0.10-alpha

- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/view/environments-view.component.html
> feat(environments): #945 colours sensitive to whether environment is build only, or build & deploy

- web/src/app/environments/view/private/environments-view-private.component.html
- web/src/assets/help/badges.md
> feat(badge): #961 Badge help and example

- web/src/app/environments/add/environments-add.component.html
- web/src/app/environments/edit/environments-edit.component.html
- web/src/app/environments/monitors/add/monitors-add.component.html
- web/src/app/environments/tokens/environments-tokens.component.html
- web/src/app/environments/tokens/token.form.ts
>  feat(environments): #903 submit disabled when invalid

- web/src/app/features/features.component.html
> fix(features): button links to login page

- web/src/app/main.component.html
> feat(navigation): #978 login/logout added to main nav

- api/src/environments/monitors/pinged/ping.js
> feat(pings): #985 invalid domain returns a 404

- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/list/environments-list.component.ts
> feat(environments): #995 renamed functions

- README.md
> Update screenshots of new UI for public environments & releases

- web/src/app/environments/releases/environments-releases.component.html
> fix(releases): #1002 display release duration

- web/src/index.html
closes #931 
Button at the bottom right...
After clicking on the button a dialog will appear...
> feat(doorbell): #931 doorbell added to app

- web/package-lock.json
- web/src/app/environments/list/environments-list.component.html
- web/src/app/environments/view/environments-view.component.html
> 1068 ui defects

- .travis.yml
- web/src/app/dialog/list/dialog-list.component.html
- web/src/app/main.component.html
- web/src/app/main.component.ts
- web/src/models/event.model.ts
- web/src/models/index.model.ts
- web/src/models/release.model.ts
- web/src/models/repository.model.ts
> Remove unused authentication service injection in main.component.ts file

- web/src/app/app-routing.module.ts
- web/src/app/projects/edit/edit.component.ts
- web/src/app/projects/view/view.component.ts
- web/src/resolvers/edit-project.resolver.ts
- web/src/resolvers/view-project.resolver.ts
closes #1192 
Kindly review and let me know in case of any question
> chore(feat): #1192, Fixed private project should not access publicly

- web/src/app/app-routing.module.ts
- web/src/app/app.component.ts
- web/src/app/app.module.ts
- web/src/app/core/guards/authentication.guard.ts
- web/src/app/core/interceptors/error.http.interceptor.ts
- web/src/app/core/interceptors/github.http.interceptor.ts
- web/src/app/core/resolvers/edit-project.resolver.ts
- web/src/app/core/resolvers/profile.resolver.ts
- web/src/app/core/resolvers/view-project.resolver.ts
- web/src/app/core/services/authentication.service.ts
- web/src/app/core/services/project.service.ts
- web/src/app/core/services/repository.service.ts
- web/src/app/core/services/user.service.ts
- web/src/app/main/components/help/help.component.ts
- web/src/app/main/components/homepage/homepage.component.ts
- web/src/app/main/components/profile/profile.component.ts
- web/src/app/projects/create/create.component.ts
- web/src/app/projects/edit/edit.component.ts
- web/src/app/projects/private/private.component.ts
- web/src/app/projects/repository/repository.component.ts
- web/src/app/projects/view/view.component.ts
- web/src/app/shared/components/projects/projects.component.ts
- web/src/app/shared/components/public/public.component.ts
- web/src/app/shared/dialog/list/dialog-list.component.ts
- web/src/app/shared/shared.module.ts
> chore(refactor): #1168 grouping import and one line comments added

- .github/PULL_REQUEST_TEMPLATE.md
> feat(docs): #1209 Updated pull request template 

- .travis.yml
> feat(deployment): #1216 updated test deployment branch

- web/src/app/core/services/authentication.service.ts
> defect(project): fixed logout issue

- web/src/app/app.component.html
- web/src/app/app.component.scss
- web/src/app/app.component.ts
- web/src/app/main/components/homepage/homepage.component.ts
- web/src/app/main/main.component.html
- web/src/app/main/main.component.ts
- web/src/app/shared/components/public/public.component.ts
> defect(project): #1224 added spinner to app module

- .travis.yml
> defect(ci): #1231 travis config branches updated

- .travis.yml
> defect(ci): #1231 travis firebase deploy message added

- .travis.yml
> feat(ci): #1235 app format version improved

- web/src/app/core/services/user.service.ts
- web/src/app/main/components/homepage/homepage.component.html
- web/src/app/main/components/homepage/homepage.component.ts
- web/src/app/pipes/pipes.module.ts
- web/src/app/pipes/user.pipe.ts
- web/src/app/shared/components/projects/projects.component.html
- web/src/app/shared/components/projects/projects.component.scss
- web/src/app/shared/components/public/public.component.ts
>  feat(project): #1214 username displayed on public project list

- web/src/app/app.component.ts
- web/src/app/core/guards/authentication.guard.ts
- web/src/app/core/interceptors/github.http.interceptor.ts
- web/src/app/core/resolvers/edit-project.resolver.ts
- web/src/app/core/resolvers/profile.resolver.ts
- web/src/app/core/resolvers/view-project.resolver.ts
- web/src/app/core/services/index.service.ts
- web/src/app/core/services/project.service.ts
- web/src/app/core/services/repository.service.ts
- web/src/app/main/components/homepage/homepage.component.ts
- web/src/app/main/components/profile/profile.component.ts
- web/src/app/pipes/index.pipe.ts
- web/src/app/pipes/pipes.module.ts
- web/src/app/pipes/user.pipe.ts
- web/src/app/projects/create-edit/create-edit.component.ts
- web/src/app/projects/repository/repository.component.ts
- web/src/app/projects/view/view.component.ts
- web/src/app/shared/components/public/public.component.ts
- web/src/app/shared/dialog/list/dialog-list.component.ts
- web/src/app/shared/models/activity.model.ts
- web/src/app/shared/models/event.model.ts
- web/src/app/shared/models/index.model.ts
- web/src/app/shared/models/profile.model.ts
> feature(project): #1227 added index file for models and pipes

- .travis.yml
> feat(functions): #1245 lint and build functions

- web/src/app/shared/dialog/markdown/dialog-markdown.component.html
- web/src/app/shared/dialog/markdown/dialog-markdown.component.scss
- web/src/app/shared/dialog/markdown/dialog-markdown.component.ts
- web/src/app/shared/directives/markdown.directive.ts
> defect(help): #1239 fixed the markdown component loading issue

- README.md
- scripts/deployment/khush.sh
> feat(devops): #1304 added more developer branches

- .travis.yml
- scripts/deployment/khush.sh
- scripts/deployment/prod.sh
- scripts/deployment/test.sh
> feat(devops): #1304 added test + prod branches for deployment

- web/package.json
> feat(web): #1313 improve dev build time

- functions/src/mappers/github/index.mapper.ts
- functions/src/mappers/github/milestone.mapper.ts
- functions/src/mappers/github/repository.mapper.ts
- functions/src/repository/info.ts
- web/src/app/projects/repository/repository.component.html
- web/src/app/projects/repository/repository.component.scss
- web/src/app/projects/repository/repository.component.ts
- web/src/app/shared/models/index.model.ts
- web/src/app/shared/models/milestone.model.ts
- web/src/app/shared/models/repository.model.ts
> feat(project): #1310 added milestone data in function and mapped on UI

- functions/src/mappers/github/release.mapper.ts
- web/src/app/core/services/index.service.ts
- web/src/app/core/services/sorting.service.ts
- web/src/app/projects/repository/repository.component.html
- web/src/app/projects/repository/repository.component.scss
- web/src/app/projects/repository/repository.component.ts
- web/src/app/shared/models/release.model.ts
> feat(project): #1316 added data to latest release card

- README.md
> docs(quickstart): deployment required

- firestore.indexes.json
> feat(db): #1321 added missing index

- web/src/app/core/services/sorting.service.ts
- web/src/app/projects/repository/repository.component.html
- web/src/app/projects/repository/repository.component.ts
closes #1317 
-[ ] Fixed indentation issue and type issue from previous issue #1316 
-[ ] Added top contributor card data to UI
> feat(contributor): #1317 added contributor card data

- functions/src/repository/info.ts
- functions/src/user/events.ts
- functions/src/user/repos.ts
- functions/src/user/stats.ts
> fix(repo): #1322 when exception is thrown dont write to db

- functions/src/mappers/github/pullRequest.mapper.ts
- web/src/app/core/services/sorting.service.ts
- web/src/app/projects/repository/repository.component.html
- web/src/app/projects/repository/repository.component.scss
- web/src/app/projects/repository/repository.component.ts
- web/src/app/shared/models/pullRequest.model.ts
> feat(project): #1318 added latest PR data to dashboard

- web/src/app/core/services/project.service.ts
- web/src/app/projects/view/view.component.ts
> fix(project): #1326 delete unsubscribes from project

- web/src/app/app.component.scss
- web/src/app/monitors/monitor-create-edit/monitor-create-edit.component.ts
- web/src/app/monitors/monitors-list/monitors-list.component.html
- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/monitors/monitors-routing.module.ts
- web/src/app/tokens/tokens-list/tokens-list.component.html
- web/src/styles.scss
> feat(monitors/tokens): added breadcrumb in monitors and tokens

- functions/package-lock.json
- functions/src/client/ping.ts
- functions/src/index.ts
- functions/src/models/index.model.ts
- functions/src/models/monitor.model.ts
- functions/src/models/ping.model.ts
- functions/src/models/project.model.ts
- functions/src/monitor/monitor.ts
- web/src/app/monitors/monitor-create-edit/monitor-create-edit.component.html
- web/src/app/monitors/monitor-create-edit/monitor-create-edit.component.ts
- web/src/app/monitors/monitors-list/monitors-list.component.html
- web/src/app/monitors/monitors-list/monitors-list.component.ts
> feat(functions): #1350 added function to ping a monitor

- firestore.indexes.json
- firestore.rules
- functions/package.json
- functions/src/index.ts
- functions/src/models/ping.model.ts
- functions/src/monitor/monitor.ts
- web/src/app/core/resolvers/ping.resolver.ts
- web/src/app/core/resolvers/pings.resolver.ts
- web/src/app/core/services/index.service.ts
- web/src/app/core/services/monitor.service.ts
- web/src/app/core/services/ping.service.ts
- web/src/app/monitors/monitors-list/monitors-list.component.html
- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/monitors/monitors-routing.module.ts
- web/src/app/monitors/monitors.module.ts
- web/src/app/monitors/pings-list/pings-list.component.html
- web/src/app/monitors/pings-list/pings-list.component.ts
- web/src/app/shared/models/index.model.ts
- web/src/app/shared/models/ping.model.ts
- web/src/app/shared/models/project.model.ts
> Display a list of pings

- functions/src/models/monitor.model.ts
- functions/src/monitor/monitor.ts
- web/src/app/monitors/monitors-list/monitors-list.component.html
- web/src/app/monitors/monitors-list/monitors-list.component.scss
- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/monitors/pings-list/pings-list.component.html
- web/src/app/shared/components/projects-list/projects-list.component.scss
- web/src/styles.scss
> feat(monitor): added time in pings list

- functions/src/index.ts
- functions/src/monitor/monitor.ts
- functions/src/project/delete-project.ts
- functions/src/scheduler/schedule.ts
- web/src/app/core/services/monitor.service.ts
- web/src/app/core/services/project.service.ts
- web/src/app/monitors/monitors-list/monitors-list.component.html
- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/tokens/tokens-create-edit/tokens-create-edit.component.html
- web/src/app/tokens/tokens-create-edit/tokens-create-edit.component.ts
- web/src/app/tokens/tokens-list/tokens-list.component.html
- web/src/index.html
- web/src/styles.scss
closes #1373 
closes #1376
closes #1367 
> feat(functions): #1373 #1367 added scheduler for delete pings 

- functions/src/index.ts
- functions/src/scheduler/schedule.ts
- web/src/app/tokens/tokens-create-edit/tokens-create-edit.component.ts
> feat(pings): #1353 added function to run all monitors every 60 mins

- web/src/app/core/services/monitor.service.ts
- web/src/app/main/components/homepage/homepage.component.ts
- web/src/app/main/components/profile/profile.component.ts
- web/src/app/monitors/monitor-create-edit/monitor-create-edit.component.ts
- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/projects/create-edit/create-edit.component.ts
- web/src/app/projects/repository/repository.component.ts
- web/src/app/projects/view/view.component.ts
- web/src/app/shared/components/private-public-project/private-public-project.component.ts
- web/src/app/shared/dialog/list/dialog-list.component.ts
- web/src/app/tokens/tokens-create-edit/tokens-create-edit.component.ts
- web/src/index.html
> feat(app): #1366 updated ngOnDestroy method in all components

- functions/src/index.ts
- functions/src/models/ping.model.ts
- functions/src/monitor/monitor.ts
- web/src/app/core/services/monitor.service.ts
- web/src/app/monitors/pings-list/pings-list.component.html
- web/src/app/projects/create-edit/create-edit.component.ts
- web/src/app/shared/models/ping.model.ts
> feat(monitors): #1379 added type in ping model

- web/src/app/projects/view/view.component.html
> feat(projects): #1383 added badges on monitors , tokens and repo

- .travis.yml
> disabling tests to get asset path updates out

- web/src/app/app.component.ts
> fix(assets): assets path updated

- web/src/app/core/resolvers/edit-project.resolver.ts
- web/src/app/core/resolvers/view-project.resolver.ts
- web/src/app/core/services/monitor.service.ts
- web/src/app/core/services/ping.service.ts
- web/src/app/core/services/project.service.ts
- web/src/app/projects/monitor-summary/monitor-summary.component.html
- web/src/app/projects/monitor-summary/monitor-summary.component.ts
- web/src/app/projects/view/view.component.html
- web/src/app/projects/view/view.component.ts
- web/src/app/shared/components/projects-list/projects-list.component.html
- web/src/app/shared/components/projects-list/projects-list.component.scss
- web/src/app/shared/components/projects-list/projects-list.component.ts
- web/src/app/shared/models/monitor.model.ts
- web/src/app/shared/models/project.model.ts
> feat(project): #1385 Added total monitors and pings info on homepage

- web/src/app/projects/create-edit/create-edit.component.html
- web/src/app/projects/create-edit/create-edit.component.ts
- web/src/app/projects/view/view.component.html
- web/src/app/shared/components/projects-list/projects-list.component.html
- web/src/app/shared/models/project.model.ts
> feat(project): #1389 added project logo url field

- firestore.rules
- web/src/app/core/services/project-token.service.ts
- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/projects/view/view.component.ts
- web/src/app/shared/dialog/confirmation/dialog-confirmation.component.html
- web/src/app/tokens/tokens-list/tokens-list.component.html
- web/src/app/tokens/tokens-list/tokens-list.component.ts
> feat(project): added confirmation dialog in monitor , token and project

- web/package-lock.json
- web/package.json
- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/shared/directives/markdown.directive.ts
- web/tsconfig.json
- web/tslint.json
> feat(app): added tslint rule for unused imports

- .travis.yml
- web/.gitignore
- web/cypress.json
- web/package-lock.json
- web/package.json
- web/test/integration/landing.feature
- web/test/plugins/index.js
- web/test/step_definitions/browser.js
- web/test/support/index.js
> feat(test): #1407 setup cypress and cucumber setup

- functions/package-lock.json
- web/package-lock.json
- web/package.json
> chore(project): #1415 fixed 544 npm vulnerabilities

- functions/src/repository/delete-git-webhook-repository.ts
- functions/src/repository/info.ts
- functions/src/user/repos.ts
- web/src/app/projects/repository/repository.component.html
- web/src/app/shared/dialog/list/dialog-list.component.html
- web/src/app/shared/dialog/list/dialog-list.component.ts
> fix(repository): #1421 list owner public repos

- web/src/app/projects/create-edit/create-edit.component.html
> fix(project): #1430 removed relative path from routerLinks

- functions/src/monitor/monitor.ts
- web/src/app/shared/models/project.model.ts
> fix(project): #1427 fixed ping count issue on project page

- firestore.rules
- functions/src/index.ts
- functions/src/project/project.ts
- web/src/app/core/resolvers/view-project.resolver.ts
- web/src/app/core/services/project.service.ts
> fix(project): #1435 fixed view project when guest login

- web/src/app/app-routing.module.ts
- web/src/app/error/error-routing.module.ts
- web/src/app/error/error.component.html
- web/src/app/error/error.component.scss
- web/src/app/error/error.component.ts
- web/src/app/error/error.module.ts
> feat(error): #1422 Error module and 404 page

- web/src/app/projects/repository/repository.component.html
- web/src/app/projects/repository/repository.component.ts
> fix(repository): #1429 fixed the flickering of webhook error message

- firestore.rules
- functions/src/application/stats.ts
- functions/src/client/firebase-admin.ts
- functions/src/index.ts
> feat(functions): #1446 functions for application stats added

- web/src/app/core/services/application.service.ts
- web/src/app/main/components/homepage/homepage.component.html
- web/src/app/main/components/stats/stats.component.html
- web/src/app/main/components/stats/stats.component.scss
- web/src/app/main/components/stats/stats.component.ts
- web/src/app/main/main.module.ts
- web/src/app/shared/models/index.model.ts
- web/src/app/shared/models/stats.model.ts
> feat(main): #1454 added application stats card on homepage

- web/src/app/monitors/monitors-list/monitors-list.component.ts
- web/src/app/projects/repository/repository.component.html
- web/src/app/projects/repository/repository.component.scss
- web/src/app/projects/repository/repository.component.ts
> feat(projects): #1438 added manual refresh button on repo list

- web/src/app/main/components/features/features.component.html
- web/src/app/main/components/features/features.component.ts
> feat(features): #1443 Updated feature list

- web/src/app/app.component.html
- web/src/app/app.component.ts
> feat(app): #1473 commented the privacy + terms and condition

- web/src/app/main/components/stats/stats.component.html
- web/src/app/projects/create-edit/create-edit.component.html
> fix(projects): #1477 disabled private project button 

- README.md
- functions/src/environments/environment.ts
- functions/src/repository/response-git-webhook-repository.ts
- scripts/deployment/dev.sh
- scripts/deployment/eddie.sh
- scripts/deployment/khush.sh
- scripts/deployment/prod.sh
- web/src/app/core/services/authentication.service.ts
> feat(config): #1442 function url to CI

- README.md
- functions/package-lock.json
- functions/src/environments/environment.ts
- functions/src/repository/create-git-webhook-repository.ts
- functions/src/repository/response-git-webhook-repository.ts
- scripts/deployment/dev.sh
- scripts/deployment/eddie.sh
- scripts/deployment/khush.sh
- scripts/deployment/prod.sh
Closes #1467 
Done:
- webhooks call with `X-Hub-Signature`
- add configuration to `functions/src/environments/environment.ts`
Should be done:
- recreate exist webhooks
> feat(repositories)#1465 secure webhooks

- functions/src/user/repos.ts
> fix(repositories): #1501 increase my repo list

- web/src/app/projects/repository/repository.component.html
- web/src/app/projects/repository/repository.component.ts
- web/src/app/projects/view/view.component.html
- web/src/app/projects/view/view.component.ts
> feat(projects): #1494 added owner check for refresh 

- web/src/app/projects/view/view.component.html
- web/src/app/shared/components/projects-list/projects-list.component.html
closes #1505 
closes #1506 
closes #1507 
> fix(project): menus for owner

- .travis.yml
> feat(deploy): #1511 default dev branch / deploy

- web/src/app/core/services/project.service.ts
- web/src/app/monitors/monitor-create-edit/monitor-create-edit.component.ts
- web/src/app/projects/view/view.component.ts
- web/src/app/shared/components/projects-list/projects-list.component.ts
- web/src/app/shared/models/project.model.ts
Moved `subscribe` to components. Both deletes work and have different success action, however, the deleting from the project dashboard (view) page I get the following error. I dint get time to fix.
```
core.js:15724 ERROR TypeError: Cannot read property 'uid' of undefined
at new ProjectModel (project.model.ts:59)
at MapSubscriber.project (project.service.ts:122)
at MapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/map.js.MapSubscriber._next (map.js:35)
at MapSubscriber.push../node_modules/rxjs/_esm5/internal/Subscriber.js.Subscriber.next (Subscriber.js:53)
at SwitchMapSubscriber.push../node_modules/rxjs/_esm5/internal/operators/switchMap.js.SwitchMapSubscriber.notifyNext (switchMap.js:72)
at InnerSubscriber.push../node_modules/rxjs/_esm5/internal/InnerSubscriber.js.InnerSubsc …
```
> feat(project): #1515 subscribe in component

- web/src/app/projects/create-edit/create-edit.component.html
- web/src/app/projects/view/view.component.html
- web/src/app/projects/view/view.component.scss
- web/src/app/shared/components/projects-list/projects-list.component.html
> feat(projects): #1447 added notification alert on project

- web/src/app/core/resolvers/edit-project.resolver.ts
- web/src/app/core/resolvers/edit-token.resolver.ts
- web/src/app/core/resolvers/pings.resolver.ts
- web/src/app/core/resolvers/repository.resolver.ts
- web/src/app/core/resolvers/view-project.resolver.ts
- web/src/app/core/services/authentication.service.ts
- web/src/app/core/services/monitor.service.ts
- web/src/app/core/services/repository.service.ts
- web/src/app/core/services/sorting.service.ts
- web/src/app/main/components/features/features.component.ts
- web/src/app/shared/models/repository.model.ts
- web/tslint.json
> feat(tslint): #1498 added tslint rule for new line before return

- web/src/index.html
> feat(analytics): #1074 google analytics
